const TOGGLE_APP_THEME = 'TOGGLE_APP_THEME';


const SELECT_WORD_SET = 'SELECT_WORD_SET';
const SELECT_WORD_SET_IS_LOADING = 'SELECT_WORD_SET_IS_LOADING';
const SELECT_WORD_SET_IS_ERROR = 'SELECT_WORD_SET_IS_ERROR';


export {
  TOGGLE_APP_THEME,
  SELECT_WORD_SET,
  SELECT_WORD_SET_IS_LOADING,
  SELECT_WORD_SET_IS_ERROR
}